version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0  # Use .NET 8 SDK Docker image
    steps:
      - checkout
      - run:
          name: Install Azure Artifacts Credential Provider
          command: |
            curl -Lsfo installcredprovider.sh https://aka.ms/install-artifacts-credprovider.sh
            chmod +x installcredprovider.sh
            ./installcredprovider.sh
      - run:
          name: Restore NuGet Packages
          command: dotnet restore CircleCiTest/CircleCiTest.csproj
      - run:
          name: Build Project
          command: dotnet build CircleCiTest/CircleCiTest.csproj --configuration Release
      - run:
          name: Create NuGet Package
          command: |
            dotnet pack CircleCiTest/CircleCiTest.csproj --configuration Release --output ./nupkgs /p:Version=1.0.$CIRCLE_BUILD_NUM
      - store_artifacts:
          path: ./nupkgs
          destination: nuget-packages
      - run:
          name: Push to Azure DevOps NuGet Feed
          command: |
            dotnet nuget add source "https://pkgs.dev.azure.com/phxmn/_packaging/dependencies-shared/nuget/v3/index.json" \
              --name "AzureDevOps" --username "AzureDevOps" --password "$AZURE_DEVOPS_APIKEY" --store-password-in-clear-text
            dotnet nuget push ./nupkgs/*.nupkg --source "AzureDevOps" --api-key "$AZURE_DEVOPS_APIKEY"
      - run:
          name: Prepare .NET Tool Directory for Octopus CLI
          command: |
            mkdir -p /root/.dotnet/tools
            mkdir -p /root/.dotnet/tools/.store
            export PATH="$PATH:/root/.dotnet/tools"
      - run:
          name: Install Octopus CLI as Dotnet Tool
          command: |
            dotnet tool install -g Octopus.Cli
            export PATH="$PATH:/root/.dotnet/tools"
      - run:
          name: Create Octopus Release
          command: |
            octo create-release \
              --project "CircleCI Test" \
              --releaseNumber "1.0.$CIRCLE_BUILD_NUM" \
              --packageversion "1.0.$CIRCLE_BUILD_NUM" \
              --server "$OCTOPUS_SERVER" \
              --apiKey "$OCTOPUS_API_KEY" \

workflows:
  version: 2
  build_and_pack:
    jobs:
      - build
